version: '3.8'

services:
  db:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: usuario_microservico
    ports:
      - "3302:3306" 
    environment:
      MYSQL_DATABASE: ${DB_DATABASE}
      MYSQL_USER: ${DB_USERNAME}
      MYSQL_PASSWORD: ${DB_PASSWORD}
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
    volumes:
      - db_data:/var/lib/mysql

volumes:
  db_data:
